name: Ship

on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Setup Drake
        run: deno run -A Drakefile.ts setup-github-actions

      - name: Setup Eggs
        run: drake install-eggs

      - name: Get hatcher version
        run: drake get-version

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-template.yml
          version: ${{ env.HATCHER_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish hatcher
        run: drake ship
