name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:
  stable:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    env:
      NESTAPIKEY: ${{ secrets.NESTAPIKEY }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Setup Drake
        run: deno run -A Drakefile.ts setup-github-actions

      - name: Setup Eggs
        run: drake install-eggs

      - name: Run tests
        run: drake test

      - name: Eggs release test
        run: drake dry-ship
      
      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log

  nightly:
    name: Deno Canary

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    env:
      NESTAPIKEY: ${{ secrets.NESTAPIKEY }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Setup Drake
        run: deno run -A Drakefile.ts setup-github-actions

      - name: Setup Eggs
        run: drake install-eggs

      - name: Run tests
        run: drake test

      - name: Eggs release test
        run: drake dry-ship
      
      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: eggs-debug
          path: eggs-debug.log
